# Generated by Django 4.0.4 on 2022-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='index',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
