# Generated by Django 4.0.4 on 2022-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_rename_default_max_endscore_setting_default_max_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('lobby_name', models.CharField(max_length=50)),
                ('game_mode', models.SmallIntegerField(default=0)),
                ('map', models.CharField(max_length=50)),
                ('players', models.SmallIntegerField(default=0)),
                ('won', models.BooleanField()),
                ('forbbiden_list', models.BooleanField()),
                ('kills', models.SmallIntegerField(default=0)),
                ('deaths', models.SmallIntegerField(default=0)),
                ('duration', models.DurationField(default=0)),
                ('time', models.DateField()),
                ('finished_game', models.BooleanField()),
                ('disconnected', models.BooleanField()),
                ('shot_bullets', models.SmallIntegerField(default=0)),
                ('health_reduction', models.SmallIntegerField(default=0)),
                ('refilled_ammo', models.SmallIntegerField(default=0)),
                ('got_hit', models.SmallIntegerField(default=0)),
                ('self_health_red', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
