# Generated by Django 4.0.4 on 2022-05-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0010_rename_players_statistic_players_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='finished_game',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='forbbiden_list',
            new_name='forbbiden',
        ),
    ]
