# Generated by Django 4.0.4 on 2022-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0012_rename_forbbiden_statistic_forbidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
    ]
