# Generated by Django 4.0.4 on 2022-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='player',
        ),
        migrations.DeleteModel(
            name='GameList',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
