FROM nginxinc/nginx-unprivileged:1-alpine

# Copy config files
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
COPY ./default.conf /etc/nginx/conf.d/doomstein98.conf

# temporarly change to root
USER root

# create static dir
RUN mkdir -p /vol/static
RUN chmod 755 /vol/static

# change back to restricted user
USER nginx