# Generated by Django 4.0.4 on 2022-04-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('string', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ammunition', models.IntegerField(default=30)),
                ('latency', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('damage', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('skin', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mode', models.IntegerField(default=0)),
                ('max_players', models.SmallIntegerField(default=4)),
                ('current_players', models.SmallIntegerField(default=0)),
                ('game_runtime', models.IntegerField(default=10)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.map')),
            ],
        ),
    ]
