# Generated by Django 4.0.4 on 2022-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='len',
            field=models.SmallIntegerField(default=0),
        ),
    ]
