# Generated by Django 4.0.4 on 2022-04-30 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='current_players',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2, 'To play reasonably, you should play at least with two player'), django.core.validators.MaxValueValidator(10, 'The Server can not handle more players')]))]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='game_runtime',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2, 'To play reasonably, you should play at least with two player'), django.core.validators.MaxValueValidator(10, 'The Server can not handle more players')]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='mode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammunition',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, 'The Weapon has to have at least 1 bullet')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1, 'The Weapon has to do at least one damage')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='latency',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='skin',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
