# Generated by Django 4.0.4 on 2022-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_lobby_current_players_alter_lobby_game_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='string',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
