# Generated by Django 4.0.4 on 2022-05-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_weapon_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='skin',
        ),
    ]
