# Generated by Django 4.0.4 on 2022-05-04 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0015_setting_start_position_bullet_weaponstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='No spaces', regex='([^ \n])+')]),
        ),
    ]
