# Generated by Django 4.0.4 on 2022-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0018_remove_setting_default_gamemode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0, unique=True)),
                ('setting', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
