# Generated by Django 4.0.4 on 2022-05-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0019_usedsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='mouse_degree',
            new_name='max_mouse_degree',
        ),
    ]
