# Generated by Django 4.0.4 on 2022-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0021_lobby_win_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bullet_speed',
            field=models.FloatField(default=1, help_text='In blocks/Frame'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='change_weapon_delay',
            field=models.FloatField(default=1, help_text='How many seconds does the change of weapon take to shoot again'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='player_speed',
            field=models.FloatField(default=0.1, help_text='In blocks/Frame'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rotation_speed',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='setting',
            name='spawn_lock_time',
            field=models.FloatField(default=10, help_text='How many seconds is a spawn locked after having been used or having been next to player'),
        ),
    ]
