# Generated by Django 4.0.4 on 2022-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0022_alter_setting_bullet_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bullet_speed',
            field=models.FloatField(default=0.8, help_text='In blocks/Frame'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='max_mouse_degree',
            field=models.SmallIntegerField(default=50, help_text='The maximal degrees which can be changed in one frame'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='player_speed',
            field=models.FloatField(default=0.13, help_text='In blocks/Frame'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rotation_speed',
            field=models.FloatField(default=0.04),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tick_rate',
            field=models.FloatField(default=0.017),
        ),
    ]
