# Generated by Django 4.0.4 on 2022-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0023_alter_setting_bullet_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='rotation_speed',
            field=models.FloatField(default=0.004),
        ),
    ]
