# Generated by Django 4.0.4 on 2022-05-07 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0024_alter_setting_rotation_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='current_players',
        ),
        migrations.AddField(
            model_name='lobby',
            name='current_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
