# Generated by Django 4.0.4 on 2022-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0025_remove_lobby_current_players_lobby_current_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='change_weapon_invalid',
            field=models.SmallIntegerField(default=0.01, help_text='How many seconds is it not allowed to change the weapon in order to prevent errors'),
        ),
    ]
