# Generated by Django 4.0.4 on 2022-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0026_setting_change_weapon_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='countdown_start_game',
            field=models.SmallIntegerField(default=3),
        ),
    ]
