# Generated by Django 4.0.4 on 2022-05-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_settings_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
