# Generated by Django 4.0.4 on 2022-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0017_setting_mouse_degree_alter_lobby_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='default_gamemode',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='default_max_endtime',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='default_max_players',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='default_winscore',
        ),
        migrations.AlterField(
            model_name='setting',
            name='bullet_speed',
            field=models.FloatField(default=1, help_text='Get calculated as divisor'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='rotation_speed',
            field=models.FloatField(default=0.5, help_text='Get calculated as divisor'),
        ),
    ]
