# Generated by Django 4.0.4 on 2022-05-06 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0020_rename_mouse_degree_setting_max_mouse_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='win_score',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
